apiVersion: apps/v1
kind: Deployment
metadata:
  name: formsiq
  labels:
    app: formsiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formsiq
  template:
    metadata:
      labels:
        app: formsiq
    spec:
      containers:
      - name: formsiq
        image: formsiq:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: api
        - containerPort: 8501
          name: ui
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: formsiq-secrets
              key: GOOGLE_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 