apiVersion: v1
kind: Service
metadata:
  name: formsiq
spec:
  selector:
    app: formsiq
  ports:
  - name: api
    port: 8000
    targetPort: 8000
  - name: ui
    port: 8501
    targetPort: 8501
  type: LoadBalancer 